package com.zhph.payment.charge.dao;

import com.zhph.payment.charge.entity.SingleInterfaceLog;
import org.springframework.stereotype.Repository;

/**
 * 单扣dao 
 * @author kang
 * 2017年7月14日上午9:38:18
 */
@Repository
public interface SingleInterfaceLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZH_SINGLE_INTERFACE_LOG
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    int deleteByPrimaryKey(String priNumber);

    /**
     * This method was generated by MyBatis Generator.
     * <p>
     * This method corresponds to the database table ZH_SINGLE_INTERFACE_LOG
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    int insert(SingleInterfaceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZH_SINGLE_INTERFACE_LOG
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    int insertSelective(SingleInterfaceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZH_SINGLE_INTERFACE_LOG
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    SingleInterfaceLog selectByPrimaryKey(String priNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZH_SINGLE_INTERFACE_LOG
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    int updateByPrimaryKeySelective(SingleInterfaceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZH_SINGLE_INTERFACE_LOG
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(SingleInterfaceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZH_SINGLE_INTERFACE_LOG
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    int updateByPrimaryKey(SingleInterfaceLog record);
}