package com.zhph.payment.charge.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 单扣日志记录
 * 批扣日志记录
 */
public class SingleInterfaceLog implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String batchNo;
    private String priNumber;
    private String loanContractNo;
    private String paymentChannel;
    private String terminalId;
    private String requestNo;
    private String transNo;
    private Date createTime;
    private String interfaceContent;
    private String charge_type;//标识：1表示单批，2表示批扣，3，表示单扣查询，4，表示批扣查询
    //标识：0表示正常，1表示批扣循环单扣操作
    private String is_loop;//
    

    
    
    
    public String getIs_loop() {
		return is_loop;
	}

	public void setIs_loop(String is_loop) {
		this.is_loop = is_loop;
	}

	public String getCharge_type() {
		return charge_type;
	}

	public void setCharge_type(String charge_type) {
		this.charge_type = charge_type;
	}

	public String getBatchNo() {
		return batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH_SINGLE_INTERFACE_LOG.PRI_NUMBER
     *
     * @return the value of ZH_SINGLE_INTERFACE_LOG.PRI_NUMBER
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    public String getPriNumber() {
        return priNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH_SINGLE_INTERFACE_LOG.PRI_NUMBER
     *
     * @param priNumber the value for ZH_SINGLE_INTERFACE_LOG.PRI_NUMBER
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    public void setPriNumber(String priNumber) {
        this.priNumber = priNumber == null ? null : priNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH_SINGLE_INTERFACE_LOG.LOAN_CONTRACT_NO
     *
     * @return the value of ZH_SINGLE_INTERFACE_LOG.LOAN_CONTRACT_NO
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    public String getLoanContractNo() {
        return loanContractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH_SINGLE_INTERFACE_LOG.LOAN_CONTRACT_NO
     *
     * @param loanContractNo the value for ZH_SINGLE_INTERFACE_LOG.LOAN_CONTRACT_NO
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    public void setLoanContractNo(String loanContractNo) {
        this.loanContractNo = loanContractNo == null ? null : loanContractNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH_SINGLE_INTERFACE_LOG.PAYMENT_CHANNEL
     *
     * @return the value of ZH_SINGLE_INTERFACE_LOG.PAYMENT_CHANNEL
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    public String getPaymentChannel() {
        return paymentChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH_SINGLE_INTERFACE_LOG.PAYMENT_CHANNEL
     *
     * @param paymentChannel the value for ZH_SINGLE_INTERFACE_LOG.PAYMENT_CHANNEL
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    public void setPaymentChannel(String paymentChannel) {
        this.paymentChannel = paymentChannel == null ? null : paymentChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH_SINGLE_INTERFACE_LOG.TERMINAL_ID
     *
     * @return the value of ZH_SINGLE_INTERFACE_LOG.TERMINAL_ID
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    public String getTerminalId() {
        return terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH_SINGLE_INTERFACE_LOG.TERMINAL_ID
     *
     * @param terminalId the value for ZH_SINGLE_INTERFACE_LOG.TERMINAL_ID
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId == null ? null : terminalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH_SINGLE_INTERFACE_LOG.REQUEST_NO
     *
     * @return the value of ZH_SINGLE_INTERFACE_LOG.REQUEST_NO
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    public String getRequestNo() {
        return requestNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH_SINGLE_INTERFACE_LOG.REQUEST_NO
     *
     * @param requestNo the value for ZH_SINGLE_INTERFACE_LOG.REQUEST_NO
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    public void setRequestNo(String requestNo) {
        this.requestNo = requestNo == null ? null : requestNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH_SINGLE_INTERFACE_LOG.TRANS_NO
     *
     * @return the value of ZH_SINGLE_INTERFACE_LOG.TRANS_NO
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    public String getTransNo() {
        return transNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH_SINGLE_INTERFACE_LOG.TRANS_NO
     *
     * @param transNo the value for ZH_SINGLE_INTERFACE_LOG.TRANS_NO
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    public void setTransNo(String transNo) {
        this.transNo = transNo == null ? null : transNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH_SINGLE_INTERFACE_LOG.CREATE_TIME
     *
     * @return the value of ZH_SINGLE_INTERFACE_LOG.CREATE_TIME
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH_SINGLE_INTERFACE_LOG.CREATE_TIME
     *
     * @param createTime the value for ZH_SINGLE_INTERFACE_LOG.CREATE_TIME
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH_SINGLE_INTERFACE_LOG.INTERFACE_CONTENT
     *
     * @return the value of ZH_SINGLE_INTERFACE_LOG.INTERFACE_CONTENT
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    public String getInterfaceContent() {
        return interfaceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH_SINGLE_INTERFACE_LOG.INTERFACE_CONTENT
     *
     * @param interfaceContent the value for ZH_SINGLE_INTERFACE_LOG.INTERFACE_CONTENT
     *
     * @mbggenerated Mon Feb 06 10:53:36 CST 2017
     */
    public void setInterfaceContent(String interfaceContent) {
        this.interfaceContent = interfaceContent == null ? null : interfaceContent.trim();
    }
}